import test from "node:test";
import assert from "node:assert/strict";

import { stationName, describeAffectedSegment, affectedDirection } from "../src/lib/stationNames.js";

test("station codes read as names a commuter recognises", () => {
  assert.equal(stationName("NS17"), "Bishan");
  assert.equal(stationName("ns14"), "Khatib");
  assert.equal(stationName("BP1"), "Choa Chu Kang");
});

// The directory has gaps (shared/stations.json is regenerated by
// `npm run stations`); a code it lacks is shown as the code, never guessed.
test("a code missing from the directory is shown as itself", () => {
  assert.equal(stationName("ZZ99"), "ZZ99");
});

test("an LTA affected segment becomes a readable sentence", () => {
  assert.equal(
    describeAffectedSegment({ StartStation: "NS14", EndStation: "NS17", Stations: "NS14,NS15,NS17" }),
    "Between Khatib and Bishan. 3 stations: Khatib, Yio Chu Kang, Bishan."
  );
  assert.equal(describeAffectedSegment({ Stations: "NS17" }), "1 station: Bishan.");
  assert.equal(describeAffectedSegment({}), "");
});
test("LTA's direction reads as words, not a bare 'Both'", () => {
  assert.equal(affectedDirection("Both"), "both directions affected");
  assert.equal(affectedDirection("Jurong East"), "trains towards Jurong East affected");
  assert.equal(affectedDirection(""), "service affected");
});
